version: "3.3"

services:

  db_tasker:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: tasker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    volumes:
      - db_tasker_data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      ENV_PATH: docker.env
    volumes:
      - .:/code
    depends_on:
      - db_tasker
volumes:
  db_tasker_data:
